### ISSUE TITLE
FastAPI OpenAPI auto-doc breaks on `pydantic-geojson`

### ISSUE THREAD

**Issue by NGTOne** [gb-libs/pydantic-geojson#20]
Pretty much what it says on the tin. When I use this library to create Pydantic models to plug into FastAPI, its auto-documentation feature breaks with a trace like this:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/base.py", line 53, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 660, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/base.py", line 35, in call_next
    message = await recv_stream.receive()
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/anyio/streams/memory.py", line 87, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/base.py", line 55, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/redacted/Work/my-codebase/service/./my_codebase/http_server_main.py", line 62, in add_logger
    return await call_next(req)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/base.py", line 37, in call_next
    raise RuntimeError("No response returned.")
RuntimeError: No response returned.
----------------------------
Traceback (most recent call last):
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/home/redacted/miniconda3/envs/my-codebase/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 410, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAPI
components -> schemas -> PointModel -> properties -> coordinates -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> PointModel -> $ref
  field required (type=value_error.missing)
```

This creates a problem for our use case, where we rely on the auto-doc feature for internal developers and quick API integration testing.

For reference, the offending model is as simple as:
```python
from pydantic import BaseModel
from pydantic_geojson import PointModel

class MyModel(BaseModel):
    location: PointModel
```

**Comment by folt** [comment]
It is possible a basic example which reproduces an error?

**Comment by NGTOne** [comment]
> Upgrading fastapi above [0.73.0](https://github.com/tiangolo/fastapi/releases/tag/0.73.0) should fix the issue.

Yes, indeed. We updated and that seems to have resolved it.

For those using older versions, the following is sufficient to reproduce the error:
```python
from fastapi import FastAPI
from pydantic import BaseModel
from pydantic_geojson import PointModel

class MyModel(BaseModel):
    location: PointModel

app = FastAPI(
    openapi_url="/documentation/service.json",
    docs_url="/documentation/service/swagger"
)

@app.get("/foo", response_model=MyModel)
def an_endpoint():
    pass
```

Hitting the auto-doc endpoint (`/documentation/service.json`) is sufficient to trigger the error, which results in a 500 response and a FastAPI stack trace.
